// Generated by CoffeeScript 1.3.3
(function() {
  var modules;

  modules = {};

  window.define = function(name, code) {
    return modules[name] = {
      code: code,
      instance: null
    };
  };

  window.require = function(name) {
    var exports, module;
    module = modules[name];
    if (module === void 0) {
      throw 'Module not found: ' + name;
    }
    if (module.instance === null) {
      exports = {};
      exports = module.code(exports);
      module.instance = exports;
    }
    return exports;
  };

}).call(this);
